###The question is: how to efficiently determine linear independece?

In [6]:
#We have four sets of four vectors to work with, lets import scilab
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [13]:
#Now that we have numpy lets define and print our vectors
V0 = np.array([.5,.5,.5,.5])
V1 = np.array([.5,.5,-.5,-.5])
V2 = np.array([.5,-.5,.5,-.5])
V3 = np.array([-.5,.5,.5,-.5])
Y  = np.array([1,-1,2,0])

#And lets print these out in pretty transpose format:
print(V0); print(V1); print(V2); print(V3); print(Y)

[ 0.5  0.5  0.5  0.5]
[ 0.5  0.5 -0.5 -0.5]
[ 0.5 -0.5  0.5 -0.5]
[-0.5  0.5  0.5 -0.5]
[ 1 -1  2  0]


In [22]:
#Let's now define the four sets that we need to check:
S1 = np.matrix([Y,V0,V1,V3]).transpose()
S2 = np.matrix([Y,V0,V1,V2]).transpose()
S3 = np.matrix([Y,V1+V2,V2,V3]).transpose()
S4 = np.matrix([Y,V1,V2,V3]).transpose()

In [25]:
#Recall that linear independence simply means that the 
#only linear combination that equals zero is the trivial
#combination where all coefficients equal zero

#This basically means that we need to frame our problems as
#Ax=b where A is the matrix composed of our allegedly independent 
#vectors and b is the zero vector. Solving for x, if x is zero, then
#the vectors are independent, otherwise they are dependent. 
#Note that we could also test the rank of the matrix to the same end. 
#Actually ya let's just use numpy's matrix_rank method :) This uses
#SVD which definitely warrants it's own post!

np.linalg.matrix_rank(S1)

4

In [26]:
np.linalg.matrix_rank(S2)

3

In [27]:
np.linalg.matrix_rank(S3)

4

In [30]:
np.linalg.matrix_rank(S4)

4

#####Lets print a matrix for fun!
$$
\begin{bmatrix}
x_{11} & x_{12} \\
x_{21} & x_{22}
\end{bmatrix}
$$

In [31]:
A = np.matrix([[0,0,0,1],[1,0,0,0],[0,1,0,0],[0,0,1,0]])

In [32]:
A

matrix([[0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0]])

In [33]:
A**2

matrix([[0, 0, 1, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 1, 0, 0]])

In [34]:
A**4

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])